name: Gen-Multi-Platform-Render
# 社区版

on:
    pull_request:
        types:
            - closed # 仅在 PR 关闭（合并或关闭）时触发
        branches:
            - release-render # 目标分支是 release-render 1111
jobs:
    build_yakit:
        if: |
            github.event.pull_request.merged == true &&
            github.event.pull_request.head.ref == 'chore/prod-ci-file'
        runs-on: ubuntu-latest
        env:
            CI: ""
            NODE_OPTIONS: --max_old_space_size=4096

        steps:
            - name: Checkout release-render branch
              uses: actions/checkout@v4
              with:
                  ref: "release-render"
            - uses: actions/setup-node@v4
              with:
                  node-version: 18.18.2
                  # 缓存 yarn 依赖包 ↓↓↓
                  cache: "yarn"
                  cache-dependency-path: app/renderer/src/main/yarn.lock

            - run: echo ${{ github.ref }}

            - name: "Install Render Dependencies"
              run: yarn install-render
              working-directory: ./

            - name: "Build CE Render"
              working-directory: ./
              run: yarn build-render
            - name: "zip CE Render"
              run: zip -r ./app/renderer/ce.zip ./app/renderer/pages && rm -rf ./app/renderer/pages

            - name: "Show Folder"
              run: ls ./app/renderer

            - name: "Build EE Render"
              working-directory: ./
              run: yarn build-render-enterprise
            - name: "zip EE Render"
              run: zip -r ./app/renderer/ee.zip ./app/renderer/pages && rm -rf ./app/renderer/pages

            - name: View Published Content
              run: ls ./app/renderer

            - name: "Build SE Render"
              working-directory: ./
              run: yarn build-render-simple-enterprise
            - name: "zip EE Render"
              run: zip -r ./app/renderer/se.zip ./app/renderer/pages && rm -rf ./app/renderer/pages

            - name: View Published Content
              run: ls ./app/renderer

            # - name: Upload Render to oss
            #   uses: tvrcgo/upload-to-oss@master
            #   with:
            #       key-id: ${{ secrets.OSS_KEY_ID }}
            #       key-secret: ${{ secrets.OSS_KEY_SECRET }}
            #       region: oss-accelerate
            #       bucket: yaklang
            #       assets: |
            #           ./app/renderer/ce.zip:/yak/render/ce.zip
            #           ./app/renderer/ee.zip:/yak/render/ee.zip
